import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import styles from '@/app/Background.module.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const simplyRounded = localFont({
  src: "./fonts/simplyrounded.ttf",
  variable: "--font-simply-rounded",
  style: "normal",
})
const proline = localFont({
  src: "./fonts/Proelium.otf",
  variable: "--font-proline",
  style: "normal",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${proline.variable} ${geistMono.variable} ${geistSans.variable} ${simplyRounded.variable}  bg-black text-white`}
      >
        {children}
      </body>
    </html>
  );
}
